# For parameter descriptions, please refer to the template parameter files for each node.
ekf_filter_node_odom:
  ros__parameters:
    frequency: 100.0
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: imu/data
    imu0_config: 
                  [false, false, false,
                  # true,  true,  true,
                  false,  false,  false,
                  false, false, false,
                  # false, false, false,
                  true,  true,  true,
                  true, false, true]
                  # true,  false,  true] 
    imu0_queue_size: 100
    imu0_remove_gravitational_acceleration: true


    # imu1: cool/data
    # imu1_config:
    #               [false, false, false,
    #               # true,  true,  true,
    #               false,  false,  false,
    #               false, false, false,
    #               # false, false, false,
    #               true,  true,  true,
    #               true, false, true]
    #               # true,  false,  true] 
    # imu1_remove_gravitational_acceleration: true

    use_control: true
    control_config: [false, true, false, false, false, false]
    acceleration_limits: [10000.0, 0.0, 0.0, 1000.0, 1000.0, 1000.0]

    # smooth_lagged_data: true
    # history_length: 20.0

    dynamic_process_noise_covariance: true


ekf_filter_node_map:
  ros__parameters:
    frequency: 100.0
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: odometry/gps 
    odom0_config: [true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_relative: false

    # odom1: /odom
    # odom1_config: [false,  false,  false,
    #               false, false, false,
    #               false, true, false,
    #               false, false, false,
    #               false, false, false]

    imu0: imu/data
    imu0_config:
                  [false, false, false,
                  # true,  true,  true,
                  false,  false,  false,
                  false, false, false,
                  true, true, true,
                  # true,  true,  true,
                  true,  false,  true] 
    imu0_remove_gravitational_acceleration: true
    

    # imu1: cool/data
    # imu1_config:
    #               [false, false, false,
    #               # true,  true,  true,
    #               false,  false,  false,
    #               false, false, false,
    #               true, true, true,
    #               # true,  true,  true,
    #               true,  false,  true] 
    # imu1_remove_gravitational_acceleration: true


    stamped_control: false
    control_timeout: 0.2

    publish_acceleration: true

    use_control: true
    control_config: [false, true, false, false, false, false]
    acceleration_limits: [10000.0, 0.0, 0.0, 1000.0, 1000.0, 1000.0]


    # smooth_lagged_data: true
    # history_length: 20.0

    dynamic_process_noise_covariance: true

navsat_transform:
  ros__parameters:
    frequency: 100.0
    yaw_offset: 2.55 #.47   2.5 is good!!
    zero_altitude: true
    use_odometry_yaw: true

    wait_for_datum: true
    datum: [40.8531181, -74.336734, 0.00]

    # smooth_lagged_data: true
    # history_length: 20.0

csv_publisher:
  ros__parameters:
    topic_name: "/cool/data"
    gyro_file: "/media/kearfott/PBKFD-0951/delta_ang.csv"
    accel_file: "/media/kearfott/PBKFD-0951/delta_vel.csv"
    start_time_est: "2024-12-20 14:15:15"
    # skip_until_est: "2024-12-20 14:50:14"
    wait_for_service_trigger: true
    # skip_until_est: "2024-12-20 14:54:26.67"
    skip_until_est: "2024-12-20 14:54:42.37"
    # skip_until_est: "2024-12-20 14:57:24.67"
    downsample_hz: 30.0
    imu_orientation_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01] # Covariance for IMU orientation
    imu_angular_velocity_covariance: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001] # Covariance for angular velocity
    imu_linear_acceleration_covariance: [0.001, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.001] # Covariance for linear acceleration

new_converter_node:
  ros__parameters:
    imu_topic_in: "/mems/raw" # IMU topic name
    imu_topic_out: "/imu/data" # Output IMU topic name
    camera_topic_in: "/camera/image_raw"
    camera_topic_out: "/camera/image"
    # start_est_time: "2024-12-20 14:50:14" 
    start_est_time: "2024-12-20 14:54:44" 
    downsample_hz: 30.0 
    imu_orientation_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01] # Covariance for IMU orientation
    imu_angular_velocity_covariance: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001] # Covariance for angular velocity
    imu_linear_acceleration_covariance: [0.001, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.001] # Covariance for linear acceleration
