ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # The second IMU
    imu0: imu/data
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 100
    imu0_relative: false
    imu0_config:
      [false, false, false,
       true, true, true,
       false,  false,  false,
       false, false, false,
      #  true,  true,  true, 
       true,  false,  true]

    use_control: true
    control_config: [false, true, false, false, false, false]
    acceleration_limits: [10000.0, 0.0, 0.0, 1000.0, 1000.0, 1000.0]

    smooth_lagged_data: true
    history_length: 40.0

    dynamic_process_noise_covariance: true

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Odom settings
    odom0: odometry/gps
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_config: 
      [true,  true,  true, # x, y, z
       false, false, false, # roll, pitch, yaw
       false, false, false, # vx, vy, vz
       false, false, false, # vroll, vpitch, vyaw
       false, false, false] # ax, ay, az

    odom1: odometry/skyline
    odom1_queue_size: 10
    odom1_nodelay: true
    odom1_config: 
      [true,  true,  false,
       false, false, false,
       false, false, false,
       false, false, false,
       false, false, false]


    # The second IMU
    imu0: imu/data
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 100
    imu0_relative: false
    imu0_config:
      [false, false, false,
       true, true, true,
       false,  false,  false,
       false, false, false,
       true,  false,  true]

    process_noise_covariance: [ 0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.05, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    1e-7, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    2.77, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    1e-3, 0.0,    0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    1e-3, 0.0,    0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    1e-3, 0.0,    0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.14, 0.0,    0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    1e-99, 0.0,
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.145]
    publish_acceleration: true

    use_control: true
    control_config: [false, true, false, false, false, false]
    acceleration_limits: [10000.0, 0.0, 1000.0, 1000.0, 1000.0, 1000.0]

    smooth_lagged_data: true
    history_length: 40.0

    dynamic_process_noise_covariance: true

navsat_transform:
  ros__parameters:
    frequency: 10.0 
    yaw_offset: 0.0
    zero_altitude: true
    use_odometry_yaw: true
    magnetic_declination_radians: -0.0001654

    wait_for_datum: true
    datum: [40.736805291, -74.16792899233333, 0.00]

    smooth_lagged_data: true
    history_length: 40.0

message_converter_node:
  ros__parameters:

    # ---------- Odometry ----------
    odom:
      lidar:                              
        in_topic:               "/Odometry"
        out_topic:              "/odometry/lidar"
        frame_id:               "map"
        child_frame_id:         "base_link"
        toggle_service:         "/toggle_odom"
        compute_twist:          true              
        orientation_offset_deg: [0.0, 0.0, 0.0]

        # unchanged covariance blocks ↓ 
        pose_cov:  [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.05, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.005, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.005, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.005]
        twist_cov: [7.02, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 7.02, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 7.02, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, -1.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, -1.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, -1.0]

      gps_heading:
        in_topic: "/gps/heading"
        out_topic: "/odometry/gps_heading" 

        orientation_offset_deg: [0.0, 0.0, 0.0]
        orientation_flip: [1.0, 1.0, 1.0]

        compass_topic: "/viz/odom_gps_compass"
        compass_size: 300 
        compass_rate_hz: 2.0
        compass_yaw_offset_deg: 0.0


    # ---------- IMU ----------
    imu:
      nav200:
        in_topic:        "/nav200/raw"
        out_topic:       "/nav200/data"
        toggle_service:  "/toggle_imu"

        orientation_cov: [0.001, 0.0, 0.0,
                          0.0, 0.001, 0.0,
                          0.0, 0.0, 0.001]
        angular_vel_cov: [0.2, 0.0, 0.0,
                          0.0, 0.2, 0.0,
                          0.0, 0.0, 0.2]
        linear_acc_cov:  [1.02, 0.0, 0.0,
                          0.0, 1.02, 0.0,
                          0.0, 0.0, 1.02]

        compass_topic: "/viz/nav200_compass"
        compass_size: 300       
        compass_rate_hz: 2.0   
        compass_yaw_offset_deg: -513.909338  

      polaris:
        in_topic:        "/polaris/imu"
        out_topic:       "/polaris/data"
        toggle_service:  "/toggle_polaris_imu"

        orientation_cov: [0.001, 0.0, 0.0,
                          0.0, 0.001, 0.0,
                          0.0, 0.0, 0.001]
        angular_vel_cov: [0.2, 0.0, 0.0,
                          0.0, 0.2, 0.0,
                          0.0, 0.0, 0.2]
        linear_acc_cov:  [1.02, 0.0, 0.0,
                          0.0, 1.02, 0.0,
                          0.0, 0.0, 1.02]

        compass_topic: "/viz/polaris_compass"
        compass_size: 300       
        compass_rate_hz: 2.0   
        compass_yaw_offset_deg: -513.909338

      raw:
        in_topic:        "/mems/raw"
        out_topic:       "/imu/data"
        toggle_service:  "/toggle_imu"

        orientation_cov: [0.001, 0.0, 0.0,
                          0.0, 0.001, 0.0,
                          0.0, 0.0, 0.001]
        angular_vel_cov: [0.2, 0.0, 0.0,
                          0.0, 0.2, 0.0,
                          0.0, 0.0, 0.2]
        linear_acc_cov:  [1.02, 0.0, 0.0,
                          0.0, 1.02, 0.0,
                          0.0, 0.0, 1.02]
#        # ENU 
        orientation_offset_deg: [0.0, 0.0, -40.0]
        orientation_flip: [1.0, 1.0,1.0]
        # mag_topic: "/imu/mag"        
        compass_topic: "/viz/imu_compass"
        compass_size: 300        
        compass_rate_hz: 2.0     
        compass_yaw_offset_deg: 180.0


        start_enabled: true

    # ---------- GPS ----------
    gps:
      dgps:
        in_topic:            "/fix"
        out_topic:           "/gps/fix"
        toggle_service:      "/toggle_gps"
        position_cov:        [0.01, 0.0, 0.0,
                              0.0, 0.01, 0.0,
                              0.0, 0.0, 0.01]
        position_cov_type:   2

      skyline:
        in_topic:            "/skyline/fix"
        out_topic:           "/gps/skyline"
        toggle_service:      "/toggle_skyline_gps"
        position_cov:        [0.01, 0.0, 0.0,
                              0.0, 0.01, 0.0,
                              0.0, 0.0, 0.01]
        position_cov_type:   2


    img: 
      image_raw:
        in_topic: "/camera/image_raw"
        out_topic: "/camera/image"
        toggle_service: "/cam_toggle"



dgps_file_publisher: 
  ros__parameters:
    file_path: "/media/kearfott/PBKFD-104/3-3-gps-data-mems-fog.txt"  
    start_est_time: "2025-03-03 12:54:55.590000"

    broadcast_fix_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    last_known_fix_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]

    fix_broadcast_topic: "/skyline/fix"

    use_image_header_time: true  
    # publish_rate: 0.05

    time_offset_seconds: -1.4

skyline_publisher:
  ros__parameters: 
    image_source: "live"
    password: "-1"
    precompute_csv_file: "/home/kearfott/ros2_ws/03_03_25_precompute_100_Goodest.csv"
    visualize: false
    display_image: false
    use_timer: false
    publish_rate: 0.1 
    queue_images: false
    num_locations: 2
    test_all_headings: false
    aoi_storage_dir: '/media/kearfott/PBKFD-104/aoi_storage'
    sdk_or_api: 'sdk'